import { Inter } from "next/font/google";
import "./globals.css";

import NavbarWithSlideInMenu from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className="w-full">
          <NavbarWithSlideInMenu />
          <div className="w-full h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
